//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace MuaSamThoiTrang.Module.BusinessObjects.QUANLYMUASAM
{

    public partial class CT_DAT_HANG : XPObject
    {
        string fMaCT;
        public string MaCT
        {
            get { return fMaCT; }
            set { SetPropertyValue<string>(nameof(MaCT), ref fMaCT, value); }
        }
        DAT_HANG fLoaiHangDat;
        [Association(@"CT_DAT_HANGReferencesDAT_HANG")]
        public DAT_HANG LoaiHangDat
        {
            get { return fLoaiHangDat; }
            set { SetPropertyValue<DAT_HANG>(nameof(LoaiHangDat), ref fLoaiHangDat, value); }
        }
        SAN_PHAM fLoaiSP;
        [Association(@"CT_DAT_HANGReferencesSAN_PHAM")]
        public SAN_PHAM LoaiSP
        {
            get { return fLoaiSP; }
            set { SetPropertyValue<SAN_PHAM>(nameof(LoaiSP), ref fLoaiSP, value); }
        }
        long fSoLuong;
        public long SoLuong
        {
            get { return fSoLuong; }
            set { SetPropertyValue<long>(nameof(SoLuong), ref fSoLuong, value); }
        }
    }

}
