//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.ExpressApp.DC;
using DevExpress.ExpressApp;
using DevExpress.Persistent.Validation;
using DevExpress.ExpressApp.Model;
namespace MuaSamThoiTrang.Module.BusinessObjects.QUANLYMUASAM
{
    [System.ComponentModel.DisplayName("Chi tiết đặt hàng")]
    [DefaultListViewOptions(MasterDetailMode.ListViewOnly, true, NewItemRowPosition.Top)]
    [DefaultProperty("MaCT")]

    public partial class CT_DAT_HANG : XPObject
    {
        string fMaCT;
        [XafDisplayName("Mã chi tiết")]
        [RuleRequiredField("Yeucau MaCT", DefaultContexts.Save, "Phải có mã chi tiết")]
        public string MaCT
        {
            get { return fMaCT; }
            set { SetPropertyValue<string>(nameof(MaCT), ref fMaCT, value); }
        }
        DAT_HANG fLoaiHangDat;
        [Association(@"CT_DAT_HANGReferencesDAT_HANG")]
        [XafDisplayName("Mã đặt hàng")]
        public DAT_HANG LoaiHangDat
        {
            get { return fLoaiHangDat; }
            set { SetPropertyValue<DAT_HANG>(nameof(LoaiHangDat), ref fLoaiHangDat, value); }
        }
        SAN_PHAM fMaSanPham;
        [Association(@"CT_DAT_HANGReferencesSAN_PHAM")]
        [XafDisplayName("Sản phẩm")]
        public SAN_PHAM MaSanPham
        {
            get { return fMaSanPham; }
            set { SetPropertyValue<SAN_PHAM>(nameof(MaSanPham), ref fMaSanPham, value); }
        }
        long fSoLuong;
        [XafDisplayName("Số lượng")]
        public long SoLuong
        {
            get { return fSoLuong; }
            set 
            {
                bool isModified = SetPropertyValue<long>(nameof(SoLuong), ref fSoLuong, value);
                if(!IsLoading && !IsDeleted && !IsSaving)
                {
                    Tinhdong();
                }
            }
        }
        decimal fDonGia;
        [XafDisplayName("Đơn giá")]
        [ModelDefault("DisplayFormat", "{0:### ### ### ###}")]
        public Decimal DonGia
        {
            get { return fDonGia; }
            set { bool isModified = SetPropertyValue<decimal>(nameof(DonGia), ref fDonGia, value); }
        }
        decimal fTongTien;
        [XafDisplayName("Tổng tiền")]
        [ModelDefault("DisplayFormat", "{0:### ### ### ###}")]
        public Decimal TongTien
        {
            get { return fTongTien; }
            set { SetPropertyValue<decimal>(nameof(TongTien), ref fTongTien, value); }
        }
        private void Tinhdong()
        {
            decimal tien = 0;
            tien = (decimal)SoLuong * DonGia;
            TongTien = tien;
        }
        THONG_KE fMaTk;
        [Association(@"CT_DAT_HANGReferencesTHONG_KE")]
        [XafDisplayName("Mã thống kê")]
        public THONG_KE MaTk
        {
            get { return fMaTk; }
            set { SetPropertyValue<THONG_KE>(nameof(MaTk), ref fMaTk, value); }
        }
<<<<<<< HEAD
        public decimal GetDonGiaFromSanPham()
        {
            if (MaSanPham != null)
            {
                return MaSanPham.DonGia;
            }
            return 0;
=======
        HOA_DON fMaHD;
        [Association(@"CT_DAT_HANGReferencesHOA_DON")]
        [XafDisplayName("Mã hóa đơn")]
        public HOA_DON MaHD
        {
            get { return fMaHD; }
            set { SetPropertyValue<HOA_DON>(nameof(MaHD), ref fMaHD, value); }
>>>>>>> 41fd1856b43042ac3e5b0b3ac523503b0f4f9f58
        }
    }

}
