//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace MuaSamThoiTrang.Module.BusinessObjects.QUANLYMUASAM
{

    public partial class CT_DAT_HANG : XPObject
    {
        string fMaCT;
        public string MaCT
        {
            get { return fMaCT; }
            set { SetPropertyValue<string>(nameof(MaCT), ref fMaCT, value); }
        }
        DAT_HANG fLoaiHangDat;
        [Association(@"CT_DAT_HANGReferencesDAT_HANG")]
        public DAT_HANG LoaiHangDat
        {
            get { return fLoaiHangDat; }
            set { SetPropertyValue<DAT_HANG>(nameof(LoaiHangDat), ref fLoaiHangDat, value); }
        }
        SAN_PHAM fMaSanPham;
        [Association(@"CT_DAT_HANGReferencesSAN_PHAM")]
        public SAN_PHAM MaSanPham
        {
            get { return fMaSanPham; }
            set { SetPropertyValue<SAN_PHAM>(nameof(MaSanPham), ref fMaSanPham, value); }
        }
        long fSoLuong;
        public long SoLuong
        {
            get { return fSoLuong; }
            set { SetPropertyValue<long>(nameof(SoLuong), ref fSoLuong, value); }
        }
        decimal fDonGia;
        public Decimal DonGia
        {
            get { return fSoLuong; }
            set { SetPropertyValue<decimal>(nameof(DonGia), ref fDonGia, value); }
        }
        decimal fTongTien;
        public Decimal TongTien
        {
            get { return fTongTien; }
            set { SetPropertyValue<decimal>(nameof(TongTien), ref fTongTien, value); }
        }
        THONG_KE fMaTk;
        [Association(@"CT_DAT_HANGReferencesTHONG_KE")]
        public THONG_KE MaTk
        {
            get { return fMaTk; }
            set { SetPropertyValue<THONG_KE>(nameof(MaTk), ref fMaTk, value); }
        }
    }

}
