//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace MuaSamThoiTrang.Module.BusinessObjects.QUANLYMUASAM
{

    public partial class DANH_GIA : XPObject
    {
        string fMaDG;
        public string MaDG
        {
            get { return fMaDG; }
            set { SetPropertyValue<string>(nameof(MaDG), ref fMaDG, value); }
        }
        string fMoTa;
        public string MoTa
        {
            get { return fMoTa; }
            set { SetPropertyValue<string>(nameof(MoTa), ref fMoTa, value); }
        }
        USER fUserID;
        [Association(@"DANH_GIAReferencesUSER")]
        public USER UserID
        {
            get { return fUserID; }
            set { SetPropertyValue<USER>(nameof(UserID), ref fUserID, value); }
        }
    }

}
