//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.ExpressApp;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Validation;
using DevExpress.ExpressApp.Model;
namespace MuaSamThoiTrang.Module.BusinessObjects.QUANLYMUASAM
{
    [System.ComponentModel.DisplayName("Đặt hàng")]
    [DefaultListViewOptions(MasterDetailMode.ListViewOnly, true, NewItemRowPosition.Top)]
    [DefaultProperty("MaDH")]
    public partial class DAT_HANG : XPObject
    {
        string fMaDH;
        [XafDisplayName("Mã đặt hàng")]
        [RuleRequiredField("Yeucau MaDH", DefaultContexts.Save, "Phải có mã đặt hàng")]
        public string MaDH
        {
            get { return fMaDH; }
            set { SetPropertyValue<string>(nameof(MaDH), ref fMaDH, value); }
        }
        USER fNguoiDat;
        [Association(@"DAT_HANGReferencesUSER")]
        [XafDisplayName("Người đặt")]
        public USER NguoiDat
        {
            get { return fNguoiDat; }
            set { SetPropertyValue<USER>(nameof(NguoiDat), ref fNguoiDat, value); }
        }
        
        DateTime fNgayDH;
        [XafDisplayName("Ngày đặt hàng")]
        [ModelDefault("EditMask", "dd/MM/yyyy HH:mm")]
        [ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime NgayDH
        {
            get { return fNgayDH; }
            set { SetPropertyValue<DateTime>(nameof(NgayDH), ref fNgayDH, value); }
        }
        bool fTrangThai;
        [XafDisplayName("Trạng thái")]
        public bool TrangThai
        {
            get { return fTrangThai; }
            set { SetPropertyValue<bool>(nameof(TrangThai), ref fTrangThai, value); }
        }
        THONG_KE fMaTk;
        [XafDisplayName("Mã thống kê")]
        [Association(@"DAT_HANGReferencesTHONG_KE")]
        public THONG_KE MaTk
        {
            get { return fMaTk; }
            set { SetPropertyValue<THONG_KE>(nameof(MaTk), ref fMaTk, value); }
        }
        [Association(@"CT_DAT_HANGReferencesDAT_HANG")]
        public XPCollection<CT_DAT_HANG> CT_DAT_HANGs { get { return GetCollection<CT_DAT_HANG>(nameof(CT_DAT_HANGs)); } }
        
    }

}
