//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace MuaSamThoiTrang.Module.BusinessObjects.QUANLYMUASAM
{

    public partial class DAT_HANG : XPObject
    {
        string fMaDH;
        public string MaDH
        {
            get { return fMaDH; }
            set { SetPropertyValue<string>(nameof(MaDH), ref fMaDH, value); }
        }
        USER fNguoiDat;
        [Association(@"DAT_HANGReferencesUSER")]
        public USER NguoiDat
        {
            get { return fNguoiDat; }
            set { SetPropertyValue<USER>(nameof(NguoiDat), ref fNguoiDat, value); }
        }
        SAN_PHAM fLoaiSP;
        [Association(@"DAT_HANGReferencesSAN_PHAM")]
        public SAN_PHAM LoaiSP
        {
            get { return fLoaiSP; }
            set { SetPropertyValue<SAN_PHAM>(nameof(LoaiSP), ref fLoaiSP, value); }
        }
        DateTime fNgayDH;
        public DateTime NgayDH
        {
            get { return fNgayDH; }
            set { SetPropertyValue<DateTime>(nameof(NgayDH), ref fNgayDH, value); }
        }
        bool fTrangThai;
        public bool TrangThai
        {
            get { return fTrangThai; }
            set { SetPropertyValue<bool>(nameof(TrangThai), ref fTrangThai, value); }
        }
        THONG_KE fMaTk;
        [Association(@"DAT_HANGReferencesTHONG_KE")]
        public THONG_KE MaTk
        {
            get { return fMaTk; }
            set { SetPropertyValue<THONG_KE>(nameof(MaTk), ref fMaTk, value); }
        }
        [Association(@"CT_DAT_HANGReferencesDAT_HANG")]
        public XPCollection<CT_DAT_HANG> CT_DAT_HANGs { get { return GetCollection<CT_DAT_HANG>(nameof(CT_DAT_HANGs)); } }
        [Association(@"HOA_DONReferencesDAT_HANG")]
        public XPCollection<HOA_DON> HOA_DONs { get { return GetCollection<HOA_DON>(nameof(HOA_DONs)); } }
    }

}
