//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace MuaSamThoiTrang.Module.BusinessObjects.QUANLYMUASAM
{

    public partial class HOA_DON : XPObject
    {
        string fMaHD;
        public string MaHD
        {
            get { return fMaHD; }
            set { SetPropertyValue<string>(nameof(MaHD), ref fMaHD, value); }
        }
        USER fNguoiMua;
        [Association(@"HOA_DONReferencesUSER")]
        public USER NguoiMua
        {
            get { return fNguoiMua; }
            set { SetPropertyValue<USER>(nameof(NguoiMua), ref fNguoiMua, value); }
        }
        DateTime fNgayLapHD;
        public DateTime NgayLapHD
        {
            get { return fNgayLapHD; }
            set { SetPropertyValue<DateTime>(nameof(NgayLapHD), ref fNgayLapHD, value); }
        }
        DAT_HANG fThongTinHangDat;
        [Association(@"HOA_DONReferencesDAT_HANG")]
        public DAT_HANG ThongTinHangDat
        {
            get { return fThongTinHangDat; }
            set { SetPropertyValue<DAT_HANG>(nameof(ThongTinHangDat), ref fThongTinHangDat, value); }
        }
    }

}
