//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using MuaSamThoiTrang.Module.BusinessObjects.QUANLYMUASAMCode;
<<<<<<< HEAD
using DevExpress.ExpressApp.DC;
=======
using DevExpress.ExpressApp;
using DevExpress.Persistent.Base;
using DevExpress.ExpressApp.DC;
using DevExpress.ExpressApp.Model;
>>>>>>> 41fd1856b43042ac3e5b0b3ac523503b0f4f9f58
namespace MuaSamThoiTrang.Module.BusinessObjects.QUANLYMUASAM
{
    [DefaultClassOptions]
    [System.ComponentModel.DisplayName("Sản phẩm")]
    [DefaultListViewOptions(MasterDetailMode.ListViewOnly, true, NewItemRowPosition.Top)]
    [DefaultProperty("TenSP")]

    public partial class SAN_PHAM : XPObject
    {
        string fMaSP;
<<<<<<< HEAD
        [XafDisplayName("Mã sản phẩm"), Size(100)]
=======
        [XafDisplayName("Mã sản phẩm")]
>>>>>>> 41fd1856b43042ac3e5b0b3ac523503b0f4f9f58
        public string MaSP
        {
            get { return fMaSP; }
            set { SetPropertyValue<string>(nameof(MaSP), ref fMaSP, value); }
        }
        string fTenSP;
<<<<<<< HEAD
        [XafDisplayName("Tên sản phẩm"), Size(100)]

=======
        [XafDisplayName("Tên sản phẩm")]
>>>>>>> 41fd1856b43042ac3e5b0b3ac523503b0f4f9f58
        public string TenSP
        {
            get { return fTenSP; }
            set { SetPropertyValue<string>(nameof(TenSP), ref fTenSP, value); }
        }
        THUONG_HIEU fMaTH;
        [XafDisplayName("Thương hiệu")]
        [Association(@"SAN_PHAMReferencesTHUONG_HIEU")]
        public THUONG_HIEU MaTH
        {
            get { return fMaTH; }
            set { SetPropertyValue<THUONG_HIEU>(nameof(MaTH), ref fMaTH, value); }
        }
        DANH_MUC fMaDM;
        [XafDisplayName("Danh mục")]
        [Association(@"SAN_PHAMReferencesDANH_MUC")]
        public DANH_MUC MaDM
        {
            get { return fMaDM; }
            set { SetPropertyValue<DANH_MUC>(nameof(MaDM), ref fMaDM, value); }
        }
        

        decimal fDonGia;
<<<<<<< HEAD
        [XafDisplayName("Đơn giá"), Size(100)]

=======
        [XafDisplayName("Đơn giá")]
        [ModelDefault("DisplayFormat", "{0:### ### ### ###}")]
>>>>>>> 41fd1856b43042ac3e5b0b3ac523503b0f4f9f58
        public decimal DonGia
        {
            get { return fDonGia; }
            set { SetPropertyValue<decimal>(nameof(DonGia), ref fDonGia, value); }
        }
        
        string fDVT;
<<<<<<< HEAD
        [XafDisplayName("Đơn vị tính"), Size(100)]

=======
        [XafDisplayName("Đơn vị tính")]
>>>>>>> 41fd1856b43042ac3e5b0b3ac523503b0f4f9f58
        public string DVT
        {
            get { return fDVT; }
            set { SetPropertyValue<string>(nameof(DVT), ref fDVT, value); }
        }
        string fMota;
<<<<<<< HEAD
        [XafDisplayName("Mô tả"), Size(100)]

=======
        [XafDisplayName("Mô tả")]
>>>>>>> 41fd1856b43042ac3e5b0b3ac523503b0f4f9f58
        public string Mota
        {
            get { return fMota; }
            set { SetPropertyValue<string>(nameof(Mota), ref fMota, value); }
        }
        [Association(@"CT_DAT_HANGReferencesSAN_PHAM")]
        public XPCollection<CT_DAT_HANG> CT_DAT_HANGs { get { return GetCollection<CT_DAT_HANG>(nameof(CT_DAT_HANGs)); } }

    }

}
