//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace MuaSamThoiTrang.Module.BusinessObjects.QUANLYMUASAM
{

    public partial class THONG_KE : XPObject
    {
        string fMaTK;
        public string MaTK
        {
            get { return fMaTK; }
            set { SetPropertyValue<string>(nameof(MaTK), ref fMaTK, value); }
        }
        string fSoLuong;
        public string SoLuong
        {
            get { return fSoLuong; }
            set { SetPropertyValue<string>(nameof(SoLuong), ref fSoLuong, value); }
        }
        [Association(@"SAN_PHAMReferencesTHONG_KE")]
        public XPCollection<SAN_PHAM> SAN_PHAMs { get { return GetCollection<SAN_PHAM>(nameof(SAN_PHAMs)); } }
    }

}
