//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using MuaSamThoiTrang.Module.BusinessObjects.QUANLYMUASAMCode;
namespace MuaSamThoiTrang.Module.BusinessObjects.QUANLYMUASAM
{

    public partial class THONG_KE : XPObject
    {
        string fMaTK;
        public string MaTK
        {
            get { return fMaTK; }
            set { SetPropertyValue<string>(nameof(MaTK), ref fMaTK, value); }
        }
        DateTime fNgayTK;
        public DateTime NgayTK
        {
            get { return fNgayTK; }
            set { SetPropertyValue<DateTime>(nameof(NgayTK), ref fNgayTK, value); }
        }
        NHAN_VIEN fMaNV;
        [Association(@"THONG_KEReferencesNHAN_VIEN")]
        public NHAN_VIEN MaNV
        { 
            get { return fMaNV; }
            set { SetPropertyValue<NHAN_VIEN>(nameof(MaNV), ref fMaNV, value); }
        }
        [Association(@"CT_DAT_HANGReferencesTHONG_KE")]
        public XPCollection<CT_DAT_HANG> CT_DAT_HANGs { get { return GetCollection<CT_DAT_HANG>(nameof(CT_DAT_HANGs)); } }
        [Association(@"DAT_HANGReferencesTHONG_KE")]
        public XPCollection<DAT_HANG> DAT_HANGs { get { return GetCollection<DAT_HANG>(nameof(DAT_HANGs)); } }
    }

}
